name: core_module
description: A new Flutter package project.
version: 0.0.1
publish_to: 'none'

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get_it: ^7.6.4
  flutter_bloc: ^8.1.2
  hive_flutter: ^1.1.0
  uno: ^1.1.8
  http: ^1.1.0
  firebase_crashlytics: ^3.3.1
  logger: ^1.3.0
  intl: ^0.18.1
  url_launcher: ^6.1.10
  email_validator: ^2.1.17
  firebase_core: ^2.9.0 #Recursos basicos
  firebase_auth: ^4.4.0 #Autenticacao
  firebase_storage: ^11.1.0 #Armazenamento arquivos
  firebase_core_platform_interface: ^4.6.0
  flutter_modular: ^6.3.1
  cloud_firestore: ^4.4.0 #Banco de dados
  design_system:
    path: ../design_system
  lyric_module:
    path: ../lyric_module

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  hive_generator: ^2.0.0 # <-- this line
  fake_cloud_firestore: ^2.4.1+1
  bloc_test: ^9.1.1
  firebase_analytics_platform_interface: ^3.4.0
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  assets:
    - assets/data/
# To add assets to your package, add an assets section, like this:
# assets:
#   - images/a_dot_burr.jpeg
#   - images/a_dot_ham.jpeg
#
# For details regarding assets in packages, see
# https://flutter.dev/assets-and-images/#from-packages
#
# An image asset can refer to one or more resolution-specific "variants", see
# https://flutter.dev/assets-and-images/#resolution-aware

# To add custom fonts to your package, add a fonts section here,
# in this "flutter" section. Each entry in this list should have a
# "family" key with the font family name, and a "fonts" key with a
# list giving the asset and other descriptors for the font. For
# example:
# fonts:
#   - family: Schyler
#     fonts:
#       - asset: fonts/Schyler-Regular.ttf
#       - asset: fonts/Schyler-Italic.ttf
#         style: italic
#   - family: Trajan Pro
#     fonts:
#       - asset: fonts/TrajanPro.ttf
#       - asset: fonts/TrajanPro_Bold.ttf
#         weight: 700
#
# For details regarding fonts in packages, see
# https://flutter.dev/custom-fonts/#from-packages
